// Generated by npm run contracts. Edit shared/contracts.ts instead.
import { z } from "zod";

export const API_VERSION = "1";
export const RULESET_VERSION = "crew-p9-50-4";
export const SuitSchema = z.enum([
  "blue",
  "green",
  "yellow",
  "black",
  "rocket",
]);
export const CardIdSchema = z
  .string()
  .regex(/^(blue|green|yellow|black)-[1-9]$|^rocket-[1-4]$/);
export type CardId = z.infer<typeof CardIdSchema>;
export const MissionIdSchema = z.number().int().min(1).max(50);
export const CharacterIdSchema = z.enum([
  "otter", "gary", "moby-dick", "spongebob", "green-dino", "coral", "komodo",
  "hangyodon", "pingu", "ilu", "snow", "tamama", "sun", "tree", "bay",
]);
export type CharacterId = z.infer<typeof CharacterIdSchema>;
export const NicknameSchema = z.string().trim().min(1).max(16);
export const RoomSettingsSchema = z
  .object({
    name: z.string().trim().min(1).max(32),
    capacity: z.union([z.literal(3), z.literal(4), z.literal(5)]),
    missionMode: z.enum(["sequential", "random"]),
    startMission: MissionIdSchema,
  })
  .strict();
export type RoomSettings = z.infer<typeof RoomSettingsSchema>;
export const MissionSchema = z.object({
  id: MissionIdSchema,
  title: z.string(),
  summary: z.string(),
  taskCount: z.number().int().min(0).max(10),
  modifiers: z.array(z.string()),
  fivePlayerTransfer: z.boolean(),
  playable: z.boolean(),
});
export type Mission = z.infer<typeof MissionSchema>;
export const CapabilitiesSchema = z.object({
  apiVersion: z.literal(API_VERSION),
  backendReady: z.boolean(),
  rulesetVersion: z.string(),
  missions: z.array(MissionSchema),
});
export const TaskTokenSchema = z.object({
  kind: z.enum(["absolute", "relative", "omega"]),
  value: z.number().int().min(1).max(10).optional(),
});
export const PreparationAnswerSchema = z.enum(["yes", "no", "unknown", "first", "middle", "last"]);
export const PreparationSchema = z.object({
  stage: z.enum(["role", "captain_decision", "captain_distribution", "token_edit", "task_transfer", "distress_vote", "distress_cards"]),
  responses: z.record(z.string(), PreparationAnswerSchema),
  activeTaskId: z.uuid().nullable(),
  eligiblePlayerIds: z.array(z.uuid()),
  answeredPlayerIds: z.array(z.uuid()),
});
export const MissionProgressSchema = z.object({
  selectedPlayerId: z.uuid().nullable(),
  secondaryPlayerId: z.uuid().nullable(),
  silentPlayerId: z.uuid().nullable(),
  blackNineHolderId: z.uuid().nullable(),
  oneWins: z.number().int().nonnegative(),
  ninesPlayed: z.number().int().min(0).max(4).optional(),
  rocketsWon: z.array(z.number().int().min(1).max(4)),
  blackCardsWon: z.number().int().nonnegative(),
  transferApplied: z.boolean(),
  distressUsed: z.boolean(),
  distressActive: z.boolean().optional(),
  distressDirection: z.enum(["left", "right"]).nullable().optional(),
});
export const CommandSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("request_restart") }).strict(),
  z.object({ type: z.literal("vote_restart"), agree: z.boolean() }).strict(),
  z.object({ type: z.literal("set_character"), characterId: CharacterIdSchema }).strict(),
  z
    .object({
      type: z.literal("update_settings"),
      settings: RoomSettingsSchema,
    })
    .strict(),
  z.object({ type: z.literal("set_ready"), ready: z.boolean() }).strict(),
  z.object({ type: z.literal("start_mission") }).strict(),
  z.object({ type: z.literal("briefing_ready") }).strict(),
  z.object({ type: z.literal("preparation_response"), answer: PreparationAnswerSchema }).strict(),
  z.object({ type: z.literal("select_crew"), playerId: z.uuid(), secondaryPlayerId: z.uuid().optional() }).strict(),
  z.object({ type: z.literal("assign_task"), playerId: z.uuid() }).strict(),
  z.object({ type: z.literal("edit_task_tokens"), firstTaskId: z.uuid(), secondTaskId: z.uuid() }).strict(),
  z.object({ type: z.literal("reset_tokens") }).strict(),
  z.object({ type: z.literal("confirm_tokens"), firstTaskId: z.uuid().optional(), secondTaskId: z.uuid().optional() }).strict(),
  z.object({ type: z.literal("transfer_task"), taskId: z.uuid(), playerId: z.uuid() }).strict(),
  z.object({ type: z.literal("skip_transfer") }).strict(),
  z.object({ type: z.literal("request_distress"), direction: z.enum(["left", "right"]) }).strict(),
  z.object({ type: z.literal("select_distress_card"), cardId: CardIdSchema }).strict(),
  z.object({ type: z.literal("choose_task"), taskId: z.uuid() }).strict(),
  z
    .object({
      type: z.literal("communicate"),
      cardId: CardIdSchema,
      marker: z.enum(["highest", "lowest", "only", "hidden"]),
    })
    .strict(),
  z.object({ type: z.literal("play_card"), cardId: CardIdSchema }).strict(),
  z.object({ type: z.literal("advance_trick") }).strict(),
  z.object({ type: z.literal("retry_mission") }).strict(),
  z.object({ type: z.literal("next_mission") }).strict(),
]);
export type Command = z.infer<typeof CommandSchema>;
export const EnvelopeSchema = z
  .object({
    commandId: z.uuid(),
    expectedRevision: z.number().int().nonnegative(),
    attemptId: z.uuid().nullable(),
    command: CommandSchema,
  })
  .strict();
export type Envelope = z.infer<typeof EnvelopeSchema>;
export const CreateRoomSchema = z
  .object({
    commandId: z.uuid(),
    nickname: NicknameSchema,
    characterId: CharacterIdSchema.optional(),
    settings: RoomSettingsSchema,
  })
  .strict();
export type CreateRoom = z.infer<typeof CreateRoomSchema>;
export const JoinRoomSchema = z
  .object({
    commandId: z.uuid(),
    nickname: NicknameSchema,
    characterId: CharacterIdSchema.optional(),
    inviteToken: z.string().min(20).max(256),
  })
  .strict();
export type JoinRoom = z.infer<typeof JoinRoomSchema>;
export const PlayerSchema = z.object({
  id: z.uuid(),
  nickname: NicknameSchema,
  characterId: CharacterIdSchema.optional(),
  seat: z.number().int().min(0).max(4),
  ready: z.boolean(),
  briefingReady: z.boolean(),
  cardCount: z.number().int().nonnegative(),
  tricksWon: z.number().int().nonnegative(),
  isDemo: z.boolean(),
  communication: z
    .object({
      cardId: CardIdSchema,
      marker: z.enum(["highest", "lowest", "only", "hidden"]),
      played: z.boolean(),
    })
    .nullable(),
});
export const TaskSchema = z.object({
  id: z.uuid(),
  cardId: CardIdSchema,
  ownerId: z.uuid().nullable(),
  order: z.number().int().positive().nullable(),
  token: TaskTokenSchema.nullable().optional(),
  status: z.enum(["pending", "success", "failed"]),
});
export const PlaySchema = z.object({
  playerId: z.uuid(),
  cardId: CardIdSchema,
});
export const SnapshotSchema = z.object({
  apiVersion: z.literal(API_VERSION),
  roomId: z.uuid(),
  revision: z.number().int().nonnegative(),
  settings: RoomSettingsSchema,
  phase: z.enum([
    "lobby",
    "briefing",
    "task_selection",
    "preparation",
    "playing",
    "trick_result",
    "success",
    "failure",
    "campaign_complete",
  ]),
  missionId: MissionIdSchema.nullable(),
  drawnMissionIds: z.array(MissionIdSchema),
  attemptId: z.uuid().nullable(),
  attemptNumber: z.number().int().nonnegative(),
  hostId: z.uuid(),
  commanderId: z.uuid().nullable(),
  turnPlayerId: z.uuid().nullable(),
  players: z.array(PlayerSchema).min(1).max(5),
  me: z.object({
    playerId: z.uuid(),
    hand: z.array(CardIdSchema),
    legalCardIds: z.array(CardIdSchema),
    canCommunicate: z.boolean(),
  }),
  tasks: z.array(TaskSchema),
  restartVote: z.object({ requestedBy: z.uuid(), approvals: z.array(z.uuid()) }).nullable().optional(),
  preparation: PreparationSchema.nullable().optional(),
  missionProgress: MissionProgressSchema.optional(),
  hiddenTaskCount: z.number().int().nonnegative().optional(),
  trick: z.array(PlaySchema),
  lastTrick: z
    .object({ plays: z.array(PlaySchema), winnerId: z.uuid() })
    .nullable(),
  trickNumber: z.number().int().nonnegative(),
  resultReason: z.string().nullable(),
  updatedAt: z.iso.datetime(),
  rulesetVersion: z.string(),
});
export type Snapshot = z.infer<typeof SnapshotSchema>;
export const EntrySchema = z.object({
  snapshot: SnapshotSchema,
  inviteToken: z.string().nullable(),
});
export const ErrorSchema = z.object({
  error: z.object({
    code: z.string(),
    message: z.string(),
    requestId: z.string(),
    currentRevision: z.number().int().optional(),
  }),
});
export class ApiError extends Error {
  constructor(
    public code: string,
    message: string,
    public status = 400,
    public currentRevision?: number,
  ) {
    super(message);
  }
}
export type Connection =
  "connecting" | "connected" | "reconnecting" | "offline";
export interface GameService {
  readonly mode: "mock" | "supabase" | "server";
  capabilities(): Promise<z.infer<typeof CapabilitiesSchema>>;
  createRoom(input: CreateRoom): Promise<z.infer<typeof EntrySchema>>;
  joinRoom(input: JoinRoom): Promise<z.infer<typeof EntrySchema>>;
  snapshot(roomId: string): Promise<Snapshot>;
  command(roomId: string, input: Envelope): Promise<Snapshot>;
  invite(roomId: string): Promise<string>;
  subscribe(
    roomId: string,
    onRevision: (revision: number) => void,
    onConnection: (connection: Connection) => void,
  ): () => void;
  fillDemoCrew?(roomId: string): Promise<Snapshot>;
  demoStep?(roomId: string): Promise<Snapshot>;
}
